-   id: avoid-name-repetition
    name: 'Avoid name repetition'
    entry: 'run-avoid-name-repetition.sh'
    files: '\.go$'
    language: 'script'
    description: 'Avoid name repetition in Go code'
